# Project identification
sonar.projectKey=Chebah-Amine_madrid-real-estate-predictor
sonar.organization=chebah-amine

# Source code location
sonar.sources=app

# Test location
sonar.tests=app/test

# Coverage report location
sonar.python.coverage.reportPaths=app/test/coverage/coverage.xml

# Coverage exclusions (excluded files from coverage computation)
sonar.coverage.exclusions=\
  **/test/**,\
  **/config/**,\
  **/migrations/**,\
  **/__pycache__/**

# Total exclusion from sonarcube (coverage, security, code smells...)
sonar.exclusions=\
  **/test/**,\
  **/docker/**,\
  **/requirements/**,\
  **/venv/**,\
  **/.venv/**,\
  **/__pycache__/**,\
  **/*.pyc,\
  **/fixtures/**,\
  **/*.csv,\
  **/*.json

# Quality gate (github wait sonarcube job to be done)
sonar.qualitygate.wait=true